library(shiny)
library(DT)
library(RColorBrewer)
library(shinycssloaders)

# Define any Python packages needed for the app here:
PYTHON_DEPENDENCIES = c('numpy')
virtualenv_dir = Sys.getenv('VIRTUALENV_NAME')
python_path = Sys.getenv('PYTHON_PATH')
reticulate::use_virtualenv(virtualenv_dir, required = T)

ui <- fluidPage(
    
    titlePanel('Example app: Using R Shiny + reticulate'),
    
    sidebarLayout(
        
        # ---------------- Sidebar panel with changeable inputs ----------------- #
        sidebarPanel(
            
            h4('Inputs to pure R functions'),
            radioButtons('dist', 
                         'Distribution type:',
                         choices = c('Normal' = 'norm',
                                     'Uniform' = 'unif', 
                                     'Log-normal' = 'lnorm', 
                                     'Exponential' = 'exp')),
            br(),
            sliderInput('n',
                        'Number of observations:',
                        value = 5000,
                        min = 100,
                        max = 10000),
            hr(),
            
            h4('Inputs to Python functions called by reticulate'),
            textInput('str',
                      'Text to display',
                      value = 'This text is being printed by a Python function!'),
            numericInput('x',
                         'x value',
                         value = 1),
            numericInput('y',
                         'y value',
                         value = 2)
        ),
        
        # ---------------- Sidebar panel with changeable inputs ----------------- #
        mainPanel(
            # Output: Tabset w/ plot, summary, and table ----
            tabsetPanel(type = 'tabs',
                        tabPanel('Using R and Python functions', 
                                 br(),
                                 h3('Outputs generated with pure R'),
                                 br(),
                                 withSpinner(plotOutput('plot')),
                                 br(),
                                 h3('Outputs generated by Python functions via reticulate'),
                                 verbatimTextOutput('message'),
                                 br(),
                                 'Use the numpy Python package to add two numbers',
                                 verbatimTextOutput('xy')),
                        tabPanel('Architecture Info', 
                                 h3('Current architecture info'),
                                 '(These values will change when app is run locally vs on Shinyapps.io)',
                                 hr(),
                                 withSpinner(DT::dataTableOutput('sysinfo')),
                                 br(),
                                 verbatimTextOutput('which_python'),
                                 verbatimTextOutput('python_version'),
                                 verbatimTextOutput('ret_env_var'),
                                 verbatimTextOutput('venv_root')
                        )
            )
        )
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {
    
    plot_cols <- brewer.pal(11, 'Spectral')
    
    # Import python functions to R
    reticulate::source_python('python_functions.py')
    
    # Generate the requested distribution
    d <- reactive({
        dist <- switch(input$dist,
                       norm = rnorm,
                       unif = runif,
                       lnorm = rlnorm,
                       exp = rexp,
                       rnorm)
        
        return(dist(input$n))
    })
    
    # Generate a plot of the data
    output$plot <- renderPlot({
        dist <- input$dist
        n <- input$n
        
        return(hist(d(),
                    main = paste0('Distribution plot: ', dist, '(n = ', n, ')'),
                    xlab = '',
                    col = plot_cols))
    })
    
    # Test that the Python functions have been imported
    output$message <- renderText({
        return(test_string_function(input$str))
    })
    
    # Test that numpy function can be used
    output$xy <- renderText({
        z = test_numpy_function(input$x, input$y)
        return(paste0('x + y = ', z))
    })
    
    # Display info about the system running the code
    output$sysinfo <- DT::renderDataTable({
        s = Sys.info()
        df = data.frame(Info_Field = names(s),
                        Current_System_Setting = as.character(s))
        return(datatable(df, rownames = F, selection = 'none',
                         style = 'bootstrap', filter = 'none', options = list(dom = 't')))
    })
    
    # Display system path to python
    output$which_python <- renderText({
        paste0('which python: ', Sys.which('python'))
    })
    
    # Display Python version
    output$python_version <- renderText({
        rr = reticulate::py_discover_config(use_environment = 'python35_env')
        paste0('Python version: ', rr$version)
    })
    
    # Display RETICULATE_PYTHON
    output$ret_env_var <- renderText({
        paste0('RETICULATE_PYTHON: ', Sys.getenv('RETICULATE_PYTHON'))
    })
    
    # Display virtualenv root
    output$venv_root <- renderText({
        paste0('virtualenv root: ', reticulate::virtualenv_root())
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
